version: '3.5'
services:
    api1:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        ports:
            -   "8081:80"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '500M'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            S_NAME: 'api1'
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            #- './docker/8.2/supervisord-octane.conf:/etc/supervisor/conf.d/supervisord.conf'
        networks:
            - sail
        depends_on:
            - mysql
    api2:
        build:
            context: ./docker/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        ports:
            -   "8082:80"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '500M'
        environment:
            WWWUSER: '${WWWUSER}'
            S_NAME: 'api2'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            #- './docker/8.2/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        deploy:
            resources:
                limits:
                    cpus: '0.75'
                    memory: '1500M'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
#    redis:
#        image: 'redis:alpine'
#        ports:
#            - '${FORWARD_REDIS_PORT:-6379}:6379'
#        volumes:
#            - 'sail-redis:/data'
#        deploy:
#            resources:
#                limits:
#                    cpus: '0.25'
#                    memory: '512M'
#        networks:
#            - sail

    nginx: # Load Balancer
        image: nginx:latest
        volumes:
            - ./docker/8.2/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - sail
        depends_on:
            - api1
            - api2
        ports:
            - "9999:9999"
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '512MB'
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
