name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#  build:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@master
#      - name: Build
#        run: bash sail up -d
  test:
    runs-on: ubuntu-20.04
#    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: bash sail up -d
      - name: Load test
        run: |
          docker exec rinha-api1 cp .env.example .env
          docker exec rinha-api1 composer install
          docker exec rinha-api1 php artisan config:cache
          docker exec rinha-api2 composer install
          docker exec rinha-api2 php artisan config:cache
          sleep 15
          docker ps
          docker exec rinha-api1 php artisan migrate
          docker exec rinha-api1 php artisan route:cache
          docker exec rinha-api1 php artisan config:cache
          git clone --single-branch --quiet https://github.com/zanfranceschi/rinha-de-backend-2023-q3
          cd rinha-de-backend-2023-q3
          wget https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.9.5/gatling-charts-highcharts-bundle-3.9.5-bundle.zip
          unzip gatling-charts-highcharts-bundle-3.9.5-bundle.zip
          cd gatling-charts-highcharts-bundle-3.9.5
          ./bin/gatling.sh -rm local -s RinhaBackendSimulation -rd "DESCRICAO" -rf $WORKSPACE/user-files/results -sf $WORKSPACE/user-files/simulations -rsf $WORKSPACE/user-files/resources
          echo GATLING_OUTPUT_FOLDER=$(ls $WORKSPACE/user-files/results | sort | head -n 1) >> $GITHUB_ENV
        env:
          WORKSPACE: ${{ github.workspace }}/rinha-de-backend-2023-q3/stress-test
      - run: echo ${{ env.GATLING_OUTPUT_FOLDER }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/rinha-de-backend-2023-q3/stress-test/user-files/results/${{ env.GATLING_OUTPUT_FOLDER }}
          destination_dir: ${{ env.GATLING_OUTPUT_FOLDER }}
      - run: echo "[Deploying to https://andersonef.github.io/rinha-backend-2023-q3/${{ env.GATLING_OUTPUT_FOLDER }}](https://andersonef.github.io/rinha-backend-2023-q3/${{ env.GATLING_OUTPUT_FOLDER }})" >> "${GITHUB_STEP_SUMMARY}"



